version: '3'
services:
        nginx:
                image: nginx:latest
                restart: always
                ports:
                        - "80:80"
                        - "8080:8080"
                volumes:
                        - ./conf/nginx/:/etc/nginx/conf.d/
                networks:
                        - loveseulgi
        web:
                build: .
                restart: always
                networks:
                        - loveseulgi
networks:
        loveseulgi:
