version: '3'
services:
        nginx:
                image: nginx:latest
                restart: always
                ports:
                        - "80:80"
                volumes:
                        - ./nginx/:/etc/nginx/conf.d/
                        - ./static:/static
                        - ./media:/usr/src/app/media
                networks:
                        - loveseulgi
        web:
                build: .
                restart: always
                volumes:
                        - ./static:/static
                        - ./media:/media
                networks:
                        - loveseulgi
networks:
        loveseulgi:
