# Generated by Django 2.2.3 on 2019-08-01 08:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, upload_to='image/user')),
                ('content', models.TextField(default='', max_length=1024)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 8, 4, 37, 54153))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, upload_to='image/post')),
                ('content', models.TextField(default='', max_length=1024)),
                ('views', models.IntegerField(default=0)),
                ('thumbs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 8, 4, 37, 54871))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, upload_to='image/report')),
                ('category', models.CharField(choices=[('SITE', 'Site'), ('USER', 'User'), ('IMAGE', 'Image')], default='SITE', max_length=12)),
                ('content', models.TextField(default='', max_length=1024)),
                ('views', models.IntegerField(default=0)),
                ('password', models.CharField(blank=True, max_length=4)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 8, 4, 37, 55704))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 8, 4, 37, 57475))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Report')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('message', models.TextField(default='')),
                ('thumbs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 8, 4, 37, 56911))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 8, 4, 37, 56350))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Notice')),
            ],
        ),
    ]
