# Generated by Django 2.0 on 2019-03-04 07:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='image/user')),
                ('content', models.TextField(default='Content', max_length=1024)),
                ('comment', models.TextField(default='Comment', max_length=1024)),
                ('views', models.IntegerField(default=0)),
                ('thumbs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 4, 16, 1, 32, 72421))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('SITE', 'Site'), ('USER', 'User'), ('IMAGE', 'Image')], default='SITE', max_length=12)),
                ('content', models.TextField(default='Content', max_length=1024)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 4, 16, 1, 32, 72421))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
