# Generated by Django 2.0 on 2019-03-18 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20190318_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 13, 40, 28, 165638)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 13, 40, 28, 165638)),
        ),
    ]
