# Generated by Django 2.0 on 2019-03-22 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20190321_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('NOTICE', 'Notice'), ('POST', 'Post'), ('REPORT', 'Report')], default='POST', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 16, 30, 43, 635494)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/user'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 16, 30, 43, 636492)),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
