# Generated by Django 2.0 on 2019-03-22 08:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0005_auto_20190322_1754'),
        ('post', '0022_auto_20190322_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, upload_to='image/user')),
                ('content', models.TextField(default='', max_length=1024)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 54, 21, 373525))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 54, 21, 375520))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('SITE', 'Site'), ('USER', 'User'), ('IMAGE', 'Image')], default='SITE', max_length=12)),
                ('content', models.TextField(default='', max_length=1024)),
                ('views', models.IntegerField(default=0)),
                ('password', models.CharField(blank=True, max_length=4)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 54, 21, 375520))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 54, 21, 376517))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.Report')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 54, 21, 374523)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 54, 21, 375520)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
