# Generated by Django 2.0 on 2019-03-26 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_auto_20190322_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 15, 37, 26, 488859)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 15, 37, 26, 488859)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Notice'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 15, 37, 26, 488859)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 15, 37, 26, 488859)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 15, 37, 26, 488859)),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 15, 37, 26, 488859)),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Report'),
        ),
    ]
