# Generated by Django 2.0 on 2019-03-26 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20190326_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 15, 17, 576445)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 15, 17, 577443)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 15, 17, 576445)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/post'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 15, 17, 578440)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 15, 17, 577443)),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/report'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 15, 17, 578440)),
        ),
    ]
