# Generated by Django 2.2.3 on 2019-08-01 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(unique=True, upload_to='image/seulgi')),
                ('name', models.CharField(default='Seulgi', max_length=24)),
                ('title', models.CharField(max_length=64)),
                ('photo_link', models.CharField(max_length=2048)),
                ('source', models.CharField(max_length=2048)),
                ('views', models.IntegerField(default=0)),
                ('thumbs', models.IntegerField(default=0)),
                ('is_gif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_link', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('message', models.TextField(default='Comment')),
                ('thumbs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
            ],
        ),
    ]
