# Generated by Django 2.0 on 2019-03-21 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('message', models.TextField(default='Comment')),
                ('thumbs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 48, 4, 352099))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
            ],
        ),
    ]
