# Generated by Django 2.0 on 2019-03-21 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_albumcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumcomment',
            old_name='post',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='albumcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 55, 58, 178432)),
        ),
    ]
