# Generated by Django 2.0 on 2019-03-22 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190321_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 16, 30, 43, 630508)),
        ),
    ]
