# Generated by Django 2.0 on 2019-03-22 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20190322_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 54, 21, 371530)),
        ),
    ]
