# Generated by Django 2.0 on 2019-03-26 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190326_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 15, 17, 573479)),
        ),
    ]
