# Generated by Django 2.0 on 2019-03-27 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20190326_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 4, 5, 153524)),
        ),
    ]
