# Generated by Django 2.0 on 2019-03-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190314_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useralbum',
            old_name='photo',
            new_name='test',
        ),
    ]
