# Generated by Django 2.0 on 2019-03-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190318_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
