# Generated by Django 2.0 on 2019-03-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20190327_1504'),
        ('user', '0005_auto_20190318_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralbum',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='useralbum',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='photos',
            field=models.ManyToManyField(to='gallery.Album'),
        ),
        migrations.DeleteModel(
            name='UserAlbum',
        ),
    ]
